"""
Test Mode Context - Synthetic Request Tracking.

Global context system for tracking synthetic requests generated by X-Test-Mode
and Chaos experiments.

Prevents pollution of production metrics / error budget:
- is_synthetic label added automatically to every metric
- Synthetic errors excluded automatically from error budget calculation
- Redis key namespace separated automatically (xtest: prefix)

Usage:
    # Context manager form (recommended)
    with TestModeContext.start(session_id="test-123"):
        # Everything in this block is tagged as synthetic
        record_dlq_item_created(domain="payment", failure_type="timeout")

    # Manual control form
    TestModeContext.enter_synthetic_mode(session_id="test-123")
    try:
        # Handle the synthetic request
        pass
    finally:
        TestModeContext.exit_synthetic_mode()

    # Query the current state
    if TestModeContext.is_synthetic():
        print(f"Synthetic session: {TestModeContext.get_session_id()}")
"""

from __future__ import annotations

from collections.abc import Generator
from contextlib import contextmanager
from contextvars import ContextVar, Token

import structlog

logger = structlog.get_logger()

# ContextVar: whether the current request is a synthetic (test) request
_is_synthetic_request: ContextVar[bool] = ContextVar(
    "is_synthetic_request",
    default=False,
)

# ContextVar: test session identifier
_synthetic_session_id: ContextVar[str | None] = ContextVar(
    "synthetic_session_id",
    default=None,
)


class TestModeContext:
    """
    Synthetic request context manager.

    Tracks synthetic requests raised by X-Test-Mode and Chaos experiments.

    Thread-safe: uses ContextVar so each thread/coroutine keeps independent
    state.

    Attributes:
        _token_synthetic: is_synthetic ContextVar restore token
        _token_session: session_id ContextVar restore token
    """

    _token_synthetic: Token[bool] | None = None
    _token_session: Token[str | None] | None = None

    @classmethod
    @contextmanager
    def start(
        cls,
        session_id: str | None = None,
    ) -> Generator[TestModeContext, None, None]:
        """
        Start a synthetic mode context (recommended form).

        Used as a context manager, the state is restored automatically when the
        block exits.

        Args:
            session_id: Test session identifier (e.g. X-Test-Session header)

        Yields:
            TestModeContext instance

        Example:
            with TestModeContext.start(session_id="xtest-abc123"):
                # Handled as a synthetic request
                pass
        """
        token_synthetic = _is_synthetic_request.set(True)
        token_session = _synthetic_session_id.set(session_id)

        logger.debug(
            "test_mode_context.entered_synthetic_mode",
            session_id=session_id,
        )

        try:
            yield cls()
        finally:
            _is_synthetic_request.reset(token_synthetic)
            _synthetic_session_id.reset(token_session)

            logger.debug(
                "test_mode_context.exited_synthetic_mode",
                session_id=session_id,
            )

    @classmethod
    def enter_synthetic_mode(
        cls,
        session_id: str | None = None,
    ) -> None:
        """
        Enter synthetic mode manually.

        exit_synthetic_mode() must be called afterwards. Using the context
        manager (start()) is recommended instead.

        Args:
            session_id: Test session identifier
        """
        cls._token_synthetic = _is_synthetic_request.set(True)
        cls._token_session = _synthetic_session_id.set(session_id)

        logger.debug(
            "test_mode_context.manual_enter_synthetic_mode",
            session_id=session_id,
        )

    @classmethod
    def exit_synthetic_mode(cls) -> None:
        """
        Exit synthetic mode manually.

        Call only when synthetic mode was entered via enter_synthetic_mode().
        """
        if cls._token_synthetic is not None:
            _is_synthetic_request.reset(cls._token_synthetic)
            cls._token_synthetic = None

        if cls._token_session is not None:
            _synthetic_session_id.reset(cls._token_session)
            cls._token_session = None

        logger.debug("test_mode_context.manual_exit_synthetic_mode")

    @classmethod
    def is_synthetic(cls) -> bool:
        """
        Check whether the current context is a synthetic request.

        Returns:
            True if inside a synthetic/test request context
        """
        return _is_synthetic_request.get()

    @classmethod
    def get_session_id(cls) -> str | None:
        """
        Return the current synthetic session ID.

        Returns:
            Session ID, or None (not in synthetic mode, or no ID was set)
        """
        return _synthetic_session_id.get()

    @classmethod
    def get_synthetic_label_value(cls) -> str:
        """
        Return the synthetic flag as a metric label string.

        String value for use in Prometheus labels.

        Returns:
            "true" if synthetic request, "false" otherwise
        """
        return "true" if cls.is_synthetic() else "false"


# Convenience functions (module level)


def is_synthetic_context() -> bool:
    """Check whether this is a synthetic request context (convenience)."""
    return TestModeContext.is_synthetic()


def get_synthetic_session_id() -> str | None:
    """Return the current synthetic session ID (convenience)."""
    return TestModeContext.get_session_id()


@contextmanager
def synthetic_context(
    session_id: str | None = None,
) -> Generator[TestModeContext, None, None]:
    """
    Synthetic mode context (convenience).

    Alias for TestModeContext.start().

    Args:
        session_id: Test session identifier

    Returns:
        Context manager yielding TestModeContext
    """
    with TestModeContext.start(session_id=session_id) as ctx:
        yield ctx
