name: ClusterFuzzLite batch fuzzing

# Daily longer fuzzing run across all harnesses (mode: batch).
on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1  # v1
        with:
          language: python
          sanitizer: address
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1  # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: batch
          sanitizer: address
